FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps/user-app/package.json ./apps/user-app/package.json
COPY apps/bank-webhook/package.json ./apps/bank-webhook/package.json

RUN npm install

COPY packages/db ./packages/db
RUN npm run db:generate

COPY apps ./apps
COPY packages ./packages

RUN npm run build

CMD ["npm", "run", "start-bankwebhook"]
